✨Added Linkedin Authentication
harshgoel05/insolvers pull request #3
Opened 2021-03-26 15:28 UTC by PushkarDureja

2021-03-26 15:29 UTC, PushkarDureja commented
@harshgoel05 have a look

2021-03-26 15:44 UTC, harshgoel05 requested changes

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-controller.ts
> +  router.get("/:provider/:token", handleFetchUserData);
token and provider should be accessed through Headers in case of non auth APIs ( user fetching and all)

=> refer authenticate function

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +  profilePicture?: string;
avatar is a better word for profilePicture

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +      "https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))",
make axios URLs go in constants

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +      firstName: userProfile["firstName"]["localized"]["en_US"],
```suggestion
      firstName:  userProfile.firstName.localized.en_US,
```

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +export async function upsertData(data: UserDataArgs) {
```suggestion
export async function upsertUser(data: UserDataArgs) {
```

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +      .findOneAndUpdate(query, update, options);
Pass query, update options here itself.

There are 2 ways: 
1. Pass these in params
2. Directly code it inside query

as you can't make it reuseable in this case; better to give it inside query

2021-03-26 15:44 UTC, harshgoel05 commented on api/user/user-service.ts
> +      return { ...data, _id: user.lastErrorObject.upserted };
what if upsert count is 0?

2021-03-27 05:07 UTC, harshgoel05 approved these changes

2021-03-27 05:07 UTC, merged